spring:
  datasource:
    url: jdbc:postgresql://<RAILWAY_POSTGRES_HOST>:<RAILWAY_POSTGRES_PORT>/<RAILWAY_POSTGRES_DB>
    username: <RAILWAY_POSTGRES_USER>
    password: <RAILWAY_POSTGRES_PASSWORD>
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
